// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VC_SL.Data;

#nullable disable

namespace VC_SL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212175436_CombatFields")]
    partial class CombatFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VC_SL.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UsernameHistory")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username_history");

                    b.HasKey("Id");

                    b.ToTable("User", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("VC_SL.Models.Entities.Winrate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttackDraw")
                        .HasColumnType("int")
                        .HasColumnName("baseAttackDraw");

                    b.Property<int>("BaseAttackLoss")
                        .HasColumnType("int")
                        .HasColumnName("baseAttackLoss");

                    b.Property<int>("BaseAttackWin")
                        .HasColumnType("int")
                        .HasColumnName("baseAttackWin");

                    b.Property<float?>("BaseAttackWinrate")
                        .HasColumnType("float")
                        .HasColumnName("baseAttackWinrate");

                    b.Property<int>("BaseDefenceDraw")
                        .HasColumnType("int")
                        .HasColumnName("baseDefenceDraw");

                    b.Property<int>("BaseDefenceLoss")
                        .HasColumnType("int")
                        .HasColumnName("baseDefenceLoss");

                    b.Property<int>("BaseDefenceWin")
                        .HasColumnType("int")
                        .HasColumnName("baseDefenceWin");

                    b.Property<float?>("BaseDefenceWinrate")
                        .HasColumnType("float")
                        .HasColumnName("baseDefenceWinrate");

                    b.Property<int>("FleetDraw")
                        .HasColumnType("int")
                        .HasColumnName("fleetDraw");

                    b.Property<int>("FleetLoss")
                        .HasColumnType("int")
                        .HasColumnName("fleetLoss");

                    b.Property<int>("FleetWin")
                        .HasColumnType("int")
                        .HasColumnName("fleetWin");

                    b.Property<float?>("FleetWinrate")
                        .HasColumnType("float")
                        .HasColumnName("fleetWinrate");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("Winrates");
                });
#pragma warning restore 612, 618
        }
    }
}
